# Generated by Django 6.0.1 on 2026-01-16 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediahub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Proposition en attente'), ('USER_APPROVED', 'Validée par le vendeur'), ('USER_REJECTED', 'Rejetée par le vendeur'), ('ADMIN_APPROVED', 'Validée par l’équipe'), ('ADMIN_REJECTED', 'Rejetée par l’équipe'), ('EDITED', 'Modifiée')], db_index=True, default='PENDING', max_length=16)),
                ('is_cached_result', models.BooleanField(db_index=True, default=False, help_text='True when suggestions are reused from a previous hash match.')),
                ('title_suggested', models.CharField(blank=True, default='', max_length=120)),
                ('description_suggested', models.TextField(blank=True, default='')),
                ('category_suggested', models.CharField(blank=True, default='', max_length=64)),
                ('price_low', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_high', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_items', to='mediahub.batchupload')),
                ('hero_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_for_items', to='mediahub.mediaasset')),
            ],
        ),
    ]
