# Generated by Django 6.0.1 on 2026-01-11 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("listings", "0001_initial"),
        (
            "mediahub",
            "0003_rename_mediahub_ba_owner_status_c_2258a1_idx_mediahub_ba_owner_i_cf00dd_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("EDITED", "Edited"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "title_suggested",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("description_suggested", models.TextField(blank=True, default="")),
                (
                    "category_suggested",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "price_low",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "price_high",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detected_items",
                        to="mediahub.batchupload",
                    ),
                ),
                (
                    "hero_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hero_for_items",
                        to="mediahub.mediaasset",
                    ),
                ),
                (
                    "listing",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="source_item",
                        to="listings.listing",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detected_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["batch", "status", "created_at"],
                        name="ingestion_d_batch_i_fd68cc_idx",
                    ),
                    models.Index(
                        fields=["owner", "status", "created_at"],
                        name="ingestion_d_owner_i_c70b02_idx",
                    ),
                ],
            },
        ),
    ]
