# Generated by Django 6.0.1 on 2026-01-20 23:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('mediahub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('DONE', 'Done'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=12)),
                ('sale_location', models.CharField(blank=True, db_index=True, max_length=140)),
                ('seller_notes', models.TextField(blank=True)),
                ('media_count', models.PositiveIntegerField(default=0)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BatchMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=12)),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('keyframe', 'Keyframe'), ('other', 'Other')], default='upload', max_length=20)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_media_asset', to='mediahub.imageasset')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to='ingestion.batchupload')),
            ],
        ),
        migrations.CreateModel(
            name='DetectedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Proposition en attente'), ('USER_APPROVED', 'Validée par le vendeur'), ('USER_REJECTED', 'Rejetée par le vendeur'), ('ADMIN_APPROVED', 'Validée par l’équipe'), ('ADMIN_REJECTED', 'Rejetée par l’équipe'), ('EDITED', 'Modifiée')], db_index=True, default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_items', to='ingestion.batchupload')),
                ('current_suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ai.aisuggestion')),
                ('hero_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_for_items', to='ingestion.batchmedia')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='batchupload',
            index=models.Index(fields=['owner', 'status', 'created_at'], name='ingestion_b_owner_i_4031a0_idx'),
        ),
        migrations.AddIndex(
            model_name='batchupload',
            index=models.Index(fields=['status', 'created_at'], name='ingestion_b_status_928c7b_idx'),
        ),
        migrations.AddIndex(
            model_name='batchmedia',
            index=models.Index(fields=['batch', 'created_at'], name='ingestion_b_batch_i_c3cc8e_idx'),
        ),
        migrations.AddIndex(
            model_name='batchmedia',
            index=models.Index(fields=['batch', 'source', 'created_at'], name='ingestion_b_batch_i_9dd455_idx'),
        ),
        migrations.AddIndex(
            model_name='batchmedia',
            index=models.Index(fields=['file_hash'], name='ingestion_b_file_ha_59f23e_idx'),
        ),
        migrations.AddIndex(
            model_name='detecteditem',
            index=models.Index(fields=['batch', 'status', 'created_at'], name='ingestion_d_batch_i_fd68cc_idx'),
        ),
        migrations.AddIndex(
            model_name='detecteditem',
            index=models.Index(fields=['owner', 'status', 'created_at'], name='ingestion_d_owner_i_c70b02_idx'),
        ),
    ]
