# Generated by Django 6.0.1 on 2026-01-16 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detecteditem',
            name='listing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_item', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='detecteditem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='detecteditem',
            index=models.Index(fields=['batch', 'status', 'created_at'], name='ingestion_d_batch_i_fd68cc_idx'),
        ),
        migrations.AddIndex(
            model_name='detecteditem',
            index=models.Index(fields=['owner', 'status', 'created_at'], name='ingestion_d_owner_i_c70b02_idx'),
        ),
    ]
