# Generated by Django 6.0.1 on 2026-01-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detecteditem",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Proposition en attente"),
                    ("USER_APPROVED", "Validée par le vendeur"),
                    ("USER_REJECTED", "Rejetée par le vendeur"),
                    ("ADMIN_APPROVED", "Validée par l’équipe"),
                    ("ADMIN_REJECTED", "Rejetée par l’équipe"),
                    ("EDITED", "Modifiée"),
                ],
                db_index=True,
                default="PENDING",
                max_length=16,
            ),
        ),
    ]
