# Generated by Django 6.0.1 on 2026-01-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_add_detecteditem_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detecteditem',
            name='metadata_json',
        ),
    ]
