# Generated by Django 6.0.1 on 2026-01-21 14:12

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=10)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('department_code', models.CharField(blank=True, max_length=3)),
                ('department_name', models.CharField(blank=True, max_length=120)),
                ('region_code', models.CharField(blank=True, max_length=3)),
                ('region_name', models.CharField(blank=True, max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'ordering': ['name', 'postal_code'],
                'indexes': [models.Index(fields=['postal_code'], name='location_city_postal_idx'), models.Index(fields=['name'], name='location_city_name_idx'), models.Index(fields=['name', 'postal_code'], name='location_city_name_postal_idx'), models.Index(django.db.models.functions.text.Lower('name'), name='location_city_name_lower_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'postal_code'), name='location_city_name_postal_uniq')],
            },
        ),
    ]
