# Generated by Django 6.0.1 on 2026-01-21 21:13

import billing.models.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_premium', models.BooleanField(db_index=True, default=False)),
                ('premium_until', models.DateTimeField(blank=True, null=True)),
                ('free_listing_quota', models.PositiveIntegerField(default=3)),
                ('free_detected_item_quota', models.PositiveIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entitlement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User entitlement',
                'verbose_name_plural': 'User entitlements',
            },
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(db_index=True, max_length=64)),
                ('period', models.DateField(db_index=True, default=billing.models.utils.current_month_period)),
                ('count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_counters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'scope', 'period'], name='billing_usa_user_id_149143_idx'), models.Index(fields=['period', 'scope'], name='billing_usa_period_5daa3f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'scope', 'period'), name='uniq_usage_counter_user_scope_period')],
            },
        ),
    ]
