# Generated by Django 6.0.1 on 2026-01-19 21:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('ingestion', '0001_initial'),
        ('location', '0001_initial'),
        ('mediahub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, db_index=True, max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('condition', models.CharField(blank=True, choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('for_parts', 'For Parts')], db_index=True, default='good', max_length=16)),
                ('price_cents', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('reserved', 'Reserved'), ('reservation_accepted', 'Reservation Accepted'), ('sold', 'Sold'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('postal_code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('city', models.CharField(blank=True, db_index=True, max_length=80)),
                ('country_code', models.CharField(default='FR', max_length=2)),
                ('available_from', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('view_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('source_type', models.CharField(default='images', max_length=12)),
                ('shipping_enabled', models.BooleanField(db_index=True, default=True)),
                ('in_person_enabled', models.BooleanField(db_index=True, default=True)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('reservation_note', models.TextField(blank=True)),
                ('moderation_notes', models.TextField(blank=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('needs_review', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='catalog.category')),
                ('location_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='location.city')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_listings', to=settings.AUTH_USER_MODEL)),
                ('reserved_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_listings', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('source_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_listing', to='ingestion.detecteditem')),
                ('source_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='mediahub.videoupload')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_role', models.CharField(choices=[('seller', 'Vendeur'), ('admin', 'Admin'), ('system', 'Système')], default='seller', max_length=16)),
                ('event', models.CharField(choices=[('submitted', 'Annonce soumise'), ('approved', 'Annonce validée'), ('rejected', 'Annonce rejetée'), ('status_updated', 'Statut modifié'), ('details_updated', 'Détails mis à jour'), ('other', 'Autre modification')], max_length=24)),
                ('details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='listings.listing')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listing_images', to='mediahub.imageasset')),
                ('keyframe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_images', to='mediahub.keyframe')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('buy', 'Acheter'), ('sell', 'Vendre'), ('both', 'Acheter & Vendre')], default='buy', max_length=10)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('radius_km', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='onboarding_profiles', to='catalog.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='listings.listing')),
            ],
            options={
                'ordering': ['-reserved_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('reserved', 'Réservé'), ('cancelled', 'Annulé'), ('accepted', 'Accepté')], db_index=True, max_length=16)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_logs', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='search_alerts', to='catalog.category')),
                ('location_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_alerts', to='location.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchAlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='listings.searchalert')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_notifications', to='listings.listing')),
            ],
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'created_at'], name='listings_li_status_29a9da_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['category', 'status', 'created_at'], name='listings_li_categor_17faf7_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['city', 'status', 'created_at'], name='listings_li_city_9bf6a5_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['postal_code', 'status', 'created_at'], name='listings_li_postal__c9017d_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['location_city', 'status', 'created_at'], name='listings_li_locatio_d905f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'listing')},
        ),
        migrations.AddIndex(
            model_name='listingimage',
            index=models.Index(fields=['listing', 'sort_order'], name='listings_li_listing_7515ff_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listingreminder',
            unique_together={('user', 'listing')},
        ),
        migrations.AddIndex(
            model_name='listingview',
            index=models.Index(fields=['user', 'listing'], name='listings_li_user_id_4594ad_idx'),
        ),
        migrations.AddIndex(
            model_name='listingview',
            index=models.Index(fields=['viewed_at'], name='listings_li_viewed__7c5802_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listingview',
            unique_together={('user', 'listing')},
        ),
        migrations.AlterUniqueTogether(
            name='searchalert',
            unique_together={('user', 'keyword', 'city', 'location_city', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='searchalertnotification',
            unique_together={('alert', 'listing')},
        ),
    ]
