# Generated by Django 6.0.1 on 2026-01-17 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('ingestion', '0002_initial'),
        ('listings', '0001_initial'),
        ('location', '0001_initial'),
        ('mediahub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchalert',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='listing',
            name='location_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='location.city'),
        ),
        migrations.AddField(
            model_name='searchalert',
            name='location_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='search_alerts', to='location.city'),
        ),
        migrations.AlterUniqueTogether(
            name='searchalert',
            unique_together={('user', 'keyword', 'city', 'location_city', 'category')},
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['location_city', 'status', 'created_at'], name='listings_li_locatio_d905f7_idx'),
        ),
    ]
