# Generated by Django 6.0.1 on 2026-01-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerlog',
            name='action',
            field=models.CharField(choices=[('created', 'Offre créée'), ('reserved', 'Réservation'), ('cancelled', 'Offre annulée'), ('accepted', 'Offre acceptée'), ('rejected', 'Offre refusée')], db_index=True, max_length=16),
        ),
    ]
