# Generated by Django 6.0.1 on 2026-01-16 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_view'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='listingview',
            new_name='listings_li_viewed__7c5802_idx',
            old_name='listingview_viewed_idx',
        ),
        migrations.AddIndex(
            model_name='listingview',
            index=models.Index(fields=['user', 'listing'], name='listings_li_user_id_4594ad_idx'),
        ),
    ]
