# Generated by Django 6.0.1 on 2026-01-21 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fulfillment', models.CharField(choices=[('shipping', 'Shipping'), ('in_person', 'In Person')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('created', 'Created'), ('meetup_scheduled', 'Meetup Scheduled'), ('in_transit', 'In Transit'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='created', max_length=24)),
                ('proposed_price_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('handover_code', models.CharField(blank=True, db_index=True, max_length=12)),
                ('handover_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_deadline', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('buyer_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_destination', to='accounts.address')),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='listings.listing')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('seller_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_as_origin', to='accounts.address')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('buyer_to_seller', 'Buyer To Seller'), ('seller_to_buyer', 'Seller To Buyer')], db_index=True, max_length=20)),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='commerce.order')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['seller', 'status', 'created_at'], name='commerce_or_seller__2ed15a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', 'status', 'created_at'], name='commerce_or_buyer_i_7b7719_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['target', 'role', 'created_at'], name='commerce_re_target__0584e1_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('order', 'role'), name='uniq_review_per_role_order'),
        ),
    ]
