# Generated by Django 6.0.1 on 2026-01-21 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('scam', 'Arnaque'), ('illegal', 'Contenu illégal'), ('inappropriate', 'Inapproprié'), ('spam', 'Spam'), ('other', 'Autre')], max_length=32)),
                ('details', models.TextField(blank=True)),
                ('target_object_id', models.CharField(db_index=True, max_length=64)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('target_snapshot', models.JSONField(blank=True, default=dict)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_created', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL)),
                ('target_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_objects', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_resolved', 'created_at'], name='reports_rep_is_reso_2be0ed_idx'), models.Index(fields=['reason', 'is_resolved', 'created_at'], name='reports_rep_reason_eaa34b_idx'), models.Index(fields=['target_content_type', 'target_object_id'], name='reports_rep_target__7985b9_idx')],
                'constraints': [models.UniqueConstraint(fields=('reporter', 'target_content_type', 'target_object_id'), name='unique_report_per_user_target')],
            },
        ),
    ]
