"""
Django settings for stillusefull project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-6j8%$en26uheoo%s_)_*s3p_*0lzgpka-0!_yoc3&0cfq@j2if"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "pwa",
    "accounts",
    "catalog",
    "mediahub",
    "listings",
    "sell",
    "commerce",
    "messaging",
    "moderation",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "stillusefull.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "stillusefull.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / ".dist" / "static"

# Auth
AUTH_USER_MODEL = "accounts.User"

# Media
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Login redirects
LOGIN_URL = "/auth/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Security uploads
DATA_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024  # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10 * 1024 * 1024

# PWA (django-pwa)
PWA_APP_NAME = "StillUseful"
PWA_APP_SHORT_NAME = "StillUseful"
PWA_APP_DESCRIPTION = "Trust-first marketplace for second-life items."
PWA_APP_THEME_COLOR = "#1F2A44"
PWA_APP_BACKGROUND_COLOR = "#F6F5F2"
PWA_APP_DISPLAY = "standalone"
PWA_APP_SCOPE = "/"
PWA_APP_START_URL = "/"
PWA_APP_STATUS_BAR_COLOR = "default"
PWA_APP_ORIENTATION = "portrait"
# PWA_APP_ICONS = [
#     {
#         "src": "/static/img/pwa/icon-192.png",
#         "sizes": "192x192",
#     },
#     {
#         "src": "/static/img/pwa/icon-512.png",
#         "sizes": "512x512",
#     },
# ]
# PWA_APP_SPLASH_SCREEN = [
#     {
#         "src": "/static/img/pwa/splash-640x1136.png",
#         "sizes": "640x1136",
#     },
#     {
#         "src": "/static/img/pwa/splash-750x1334.png",
#         "sizes": "750x1334",
#     },
#     {
#         "src": "/static/img/pwa/splash-1125x2436.png",
#         "sizes": "1125x2436",
#     },
#     {
#         "src": "/static/img/pwa/splash-1242x2208.png",
#         "sizes": "1242x2208",
#     },
#     {
#         "src": "/static/img/pwa/splash-1536x2048.png",
#         "sizes": "1536x2048",
#     },
#     {
#         "src": "/static/img/pwa/splash-1668x2224.png",
#         "sizes": "1668x2224",
#     },
#     {
#         "src": "/static/img/pwa/splash-2048x2732.png",
#         "sizes": "2048x2732",
#     },
# ]
