# Generated by Django 6.0.1 on 2026-01-22 21:10

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIImageAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('openai', 'Openai'), ('azure_openai', 'Azure Openai'), ('aws', 'Aws')], default='openai', max_length=20)),
                ('model_name', models.CharField(default='gpt-4o-mini', max_length=64)),
                ('prompt_version', models.CharField(default='v1', max_length=24)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('output_json', models.JSONField(blank=True, default=dict)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cost_eur', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10)),
                ('attempt', models.PositiveSmallIntegerField(default=0)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('suggested_category_slug', models.CharField(blank=True, max_length=64)),
                ('suggested_title', models.CharField(blank=True, max_length=120)),
                ('suggested_condition', models.CharField(blank=True, max_length=20)),
                ('suggested_attributes', models.JSONField(default=dict)),
                ('price_eur_min', models.PositiveIntegerField(blank=True, null=True)),
                ('price_eur_max', models.PositiveIntegerField(blank=True, null=True)),
                ('pricing_reason', models.CharField(blank=True, max_length=280)),
                ('quality_flags', models.JSONField(blank=True, default=list)),
                ('user_accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
