# Generated by Django 6.0.1 on 2026-01-19 12:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiimageanalysis',
            new_name='ai_aiimagea_status_a1c8fc_idx',
            old_name='ai_imageanalysis_status_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='aiimageanalysis',
            new_name='ai_aiimagea_image_a_21932b_idx',
            old_name='ai_imageanalysis_image_asset_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='aiimageanalysis',
            new_name='ai_aiimagea_listing_84dace_idx',
            old_name='ai_imageanalysis_listing_created_at_idx',
        ),
        migrations.AlterField(
            model_name='aiimageanalysis',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aiimageanalysis',
            name='provider',
            field=models.CharField(choices=[('openai', 'Openai'), ('azure_openai', 'Azure Openai'), ('aws', 'Aws')], default='openai', max_length=20),
        ),
        migrations.AlterField(
            model_name='aiimageanalysis',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16),
        ),
        migrations.AlterField(
            model_name='aisuggestion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
