# Generated by Django 6.0.1 on 2026-01-21 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('ingestion', '0001_initial'),
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiimageanalysis',
            name='image_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='ingestion.batchmedia'),
        ),
        migrations.AddField(
            model_name='aiimageanalysis',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='analysis',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion', to='ai.aiimageanalysis'),
        ),
        migrations.AddField(
            model_name='aisuggestion',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestions', to='listings.listing'),
        ),
        migrations.AddIndex(
            model_name='aiimageanalysis',
            index=models.Index(fields=['status', 'created_at'], name='ai_aiimagea_status_a1c8fc_idx'),
        ),
        migrations.AddIndex(
            model_name='aiimageanalysis',
            index=models.Index(fields=['image_asset', 'created_at'], name='ai_aiimagea_image_a_21932b_idx'),
        ),
        migrations.AddIndex(
            model_name='aiimageanalysis',
            index=models.Index(fields=['created_at'], name='ai_aiimagea_created_3e4093_idx'),
        ),
    ]
