# Generated by Django 6.0.1 on 2026-01-22 21:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='videos/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('duration_s', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Keyframe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='keyframes/%Y/%m/%d/')),
                ('timestamp_ms', models.PositiveIntegerField(db_index=True)),
                ('sharpness_score', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('is_selected', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyframes', to='mediahub.videoupload')),
            ],
        ),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('keyframe', 'Keyframe'), ('other', 'Other')], default='upload', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='mediahub_im_user_id_1950ee_idx'), models.Index(fields=['source', 'created_at'], name='mediahub_im_source_2af3bc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='videoupload',
            index=models.Index(fields=['user', 'created_at'], name='mediahub_vi_user_id_61bf7e_idx'),
        ),
        migrations.AddIndex(
            model_name='videoupload',
            index=models.Index(fields=['status', 'created_at'], name='mediahub_vi_status_ce7595_idx'),
        ),
        migrations.AddIndex(
            model_name='keyframe',
            index=models.Index(fields=['video', 'is_selected'], name='mediahub_ke_video_i_6c105d_idx'),
        ),
        migrations.AddIndex(
            model_name='keyframe',
            index=models.Index(fields=['video', 'timestamp_ms'], name='mediahub_ke_video_i_d38807_idx'),
        ),
        migrations.AddIndex(
            model_name='keyframe',
            index=models.Index(fields=['video', '-sharpness_score'], name='mediahub_ke_video_i_8cf6f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='keyframe',
            constraint=models.UniqueConstraint(fields=('video', 'timestamp_ms'), name='uniq_keyframe_video_timestamp'),
        ),
    ]
