# Generated by Django 6.0.1 on 2026-01-11 11:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mediahub", "0002_batch_upload"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="batchupload",
            new_name="mediahub_ba_owner_i_cf00dd_idx",
            old_name="mediahub_ba_owner_status_c_2258a1_idx",
        ),
        migrations.RenameIndex(
            model_name="batchupload",
            new_name="mediahub_ba_status_19b326_idx",
            old_name="mediahub_ba_status_created__44ccef_idx",
        ),
    ]
